name: Trigger Fork Repo Actions

on: 
  push:
    branches:
      - main
jobs:
  trigger-fork:
    if: github.repository_owner == 'subject-test-2'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'main branch pushed'
