name: Trigger sync

on:
  repository_dispatch:
    types: [main_updated]
    
jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    if: github.repository == 'han9898/ci-cd-copied'
    steps:
      - run: echo 'sync'
